In [25]:
import pandas as pd

raw_df=pd.read_csv('amazon_com_extras.csv',encoding='ISO-8859-1')
raw_df.head()

,ASIN,GROUP,FORMAT,TITLE,AUTHOR,PUBLISHER,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14
0,1250150183,book,hardcover,The Swamp: Washington's Murky Pool of Corrupti...,Eric Bolling,St. Martin's Press,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,778319997,book,hardcover,"Rise and Shine, Benedict Stone: A Novel",Phaedra Patrick,Park Row Books,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,1608322564,book,hardcover,Sell or Be Sold: How to Get Your Way in Busine...,Grant Cardone,Greenleaf Book Group Press,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,310325331,book,hardcover,Christian Apologetics: An Anthology of Primary...,"Khaldoun A. Sweis, Chad V. Meister",Zondervan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,312616295,book,hardcover,Gravity: How the Weakest Force in the Universe...,Brian Clegg,St. Martin's Press,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [26]:
raw_df=raw_df.drop(columns=(['Unnamed: 6','Unnamed: 7','Unnamed: 8','Unnamed: 9','Unnamed: 10','Unnamed: 11','Unnamed: 12','Unnamed: 12','Unnamed: 13','Unnamed: 14']))
raw_df.head()

,ASIN,GROUP,FORMAT,TITLE,AUTHOR,PUBLISHER
0,1250150183,book,hardcover,The Swamp: Washington's Murky Pool of Corrupti...,Eric Bolling,St. Martin's Press
1,778319997,book,hardcover,"Rise and Shine, Benedict Stone: A Novel",Phaedra Patrick,Park Row Books
2,1608322564,book,hardcover,Sell or Be Sold: How to Get Your Way in Busine...,Grant Cardone,Greenleaf Book Group Press
3,310325331,book,hardcover,Christian Apologetics: An Anthology of Primary...,"Khaldoun A. Sweis, Chad V. Meister",Zondervan
4,312616295,book,hardcover,Gravity: How the Weakest Force in the Universe...,Brian Clegg,St. Martin's Press

In [27]:
# Trim leading and trailing whitespaces from all string columns
raw_df = raw_df.apply(lambda x: x.str.strip() if x.dtype == "object" else x)

# Verify the changes
raw_df.head(5)

,ASIN,GROUP,FORMAT,TITLE,AUTHOR,PUBLISHER
0,1250150183,book,hardcover,The Swamp: Washington's Murky Pool of Corrupti...,Eric Bolling,St. Martin's Press
1,778319997,book,hardcover,"Rise and Shine, Benedict Stone: A Novel",Phaedra Patrick,Park Row Books
2,1608322564,book,hardcover,Sell or Be Sold: How to Get Your Way in Busine...,Grant Cardone,Greenleaf Book Group Press
3,310325331,book,hardcover,Christian Apologetics: An Anthology of Primary...,"Khaldoun A. Sweis, Chad V. Meister",Zondervan
4,312616295,book,hardcover,Gravity: How the Weakest Force in the Universe...,Brian Clegg,St. Martin's Press

In [30]:
encoding_issues_pattern = r'[ÃÂâ€™â€œâ€¢Ã±Ã©Â®Ã¼Ã¶â€•Ã¤â€“Ã¶ÃŸÃ³Ã¤Â¿ÃºÃ¡]'
incorrectly_encoded_titles = raw_df[raw_df['TITLE'].str.contains(encoding_issues_pattern, regex=True, na=False)]
print(incorrectly_encoded_titles[['TITLE']])

                                                   TITLE
12                        Ein Laden, der GlÃ¼ck verkauft
38     Electric Machines: Steady State, Transients, a...
46                            SÃ©ance Infernale: A novel
48                                         Der GrÃ¼ffelo
100    Pschyrembel Klinisches WÃ¶rterbuch (German Edi...
...                                                  ...
63632  And the Rest Is History: The Chronicles of St....
63665  The Kindergartener's Handbook: Bilingual (Engl...
63666                         Die DrachenflÃ¼sterer-Saga
63708    Kein ZurÃ¼ck (Kathleen Turner) (German Edition)
63742  Cartas a una extraÃ±a (Parte 1) (Spanish Edition)

[2004 rows x 1 columns]

In [7]:
encoding_issues_pattern = r'[ÃÂâ€™â€œâ€¢Ã±Ã©Â®Ã¼Ã¶â€•Ã¤â€“Ã¶ÃŸÃ³Ã¤Â¿ÃºÃ¡]'
incorrectly_encoded_author = raw_df[raw_df['AUTHOR'].str.contains(encoding_issues_pattern, regex=True, na=False)]
print(incorrectly_encoded_author[['AUTHOR']])

                                                AUTHOR
79                                     Sebastian RÃ¶dl
267                                   Francisco CantÃº
346                    Kyra SÃ¤nger, Christian SÃ¤nger
368                                    Johannes StÃ¤rk
385              Kari-Lynn Winters, FranÃ§ois Thisdale
...                                                ...
63445                           Tannia E. Ortiz-LopÃ©s
63532  Jennifer Johnson, Isaac David, ChloÃ« A. Miller
63535                   Mirjam KÃ¼nkler, Alfred Stepan
63541                  Malika Stenger, JÃ¼rgen Vormann
63664                                  Sofia HÃ¤llgren

[919 rows x 1 columns]

In [29]:
encoding_issues_pattern = r'[ÃÂâ€™â€œâ€¢Ã±Ã©Â®Ã¼Ã¶â€•Ã¤â€“Ã¶ÃŸÃ³Ã¤Â¿ÃºÃ¡]'
incorrectly_encoded_publisher = raw_df[raw_df['PUBLISHER'].str.contains(encoding_issues_pattern, regex=True, na=False)]
print(incorrectly_encoded_publisher[['PUBLISHER']])

                       PUBLISHER
403                       LÃ¼bbe
721          MÃ¼ller & Steinicke
798          MÃ¼ller & Steinicke
1324    GÃ¼tersloher Verlagshaus
2089           PropylÃ¤en Verlag
...                          ...
62373     VDM Verlag Dr. MÃ¼ller
62945  Gmeiner Verlag,MeÃkirch,
63103            Book View CafÃ©
63347                     LÃ¼bbe
63413                     LÃ¼bbe

[201 rows x 1 columns]

In [10]:
import re

# Define the regex pattern for the incorrect characters
encoding_issues_pattern = r'[ÃÂâ€™â€œâ€¢Ã±Ã©Â®Ã¼Ã¶â€•Ã¤â€“Ã³ÃŸÃºÃ¡]'

# Function to detect rows with wrong encoding in a string
def detect_wrong_encoding(text):
    if isinstance(text, str):
        return bool(re.search(encoding_issues_pattern, text))  # Returns True if wrong encoding is found
    return False

# Apply the detection function to each column and create a mask for rows with encoding issues
wrong_encoded_rows = raw_df.applymap(detect_wrong_encoding).any(axis=1)

# Extract rows with wrongly encoded data
incorrectly_encoded_df = raw_df[wrong_encoded_rows]

# Display the rows with wrong encoding
print(incorrectly_encoded_df)

C:\Users\Admin\AppData\Local\Temp\ipykernel_7116\3249985951.py:13: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  wrong_encoded_rows = raw_df.applymap(detect_wrong_encoding).any(axis=1)

             ASIN GROUP     FORMAT  \
12     3462046543  book  hardcover
38     1420055720  book  hardcover
46     1101946733  book  hardcover
48     3407792913  book  hardcover
79     067402494X  book  hardcover
...           ...   ...        ...
63664  818253660X  book  paperback
63665  1772264016  book  paperback
63666  3453534395  book  paperback
63708  1477826971  book  paperback
63742  1503937496  book  paperback

                                                   TITLE  \
12                        Ein Laden, der GlÃ¼ck verkauft
38     Electric Machines: Steady State, Transients, a...
46                            SÃ©ance Infernale: A novel
48                                         Der GrÃ¼ffelo
79                                    Self-Consciousness
...                                                  ...
63664                                        Stoneangels
63665  The Kindergartener's Handbook: Bilingual (Engl...
63666                         Die DrachenflÃ¼sterer-Saga
63708    Kein ZurÃ¼ck (Kathleen Turner) (German Edition)
63742  Cartas a una extraÃ±a (Parte 1) (Spanish Edition)

                                   AUTHOR                  PUBLISHER
12                           Beth Hoffman  Kiepenheuer & Witsch Gmbh
38     Ion Boldea, Lucian Nicolae Tutelea                  CRC Press
46                      Jonathan Skariton                      Knopf
48        Axel Scheffler, Julia Donaldson                      Beltz
79                        Sebastian RÃ¶dl   Harvard University Press
...                                   ...                        ...
63664                     Sofia HÃ¤llgren               Cyberwit.net
63665         Dayna Martin, A.R. Roumanis               Engage Books
63666                          Boris Koch               Heyne Verlag
63708      Tiffany Snow, Miriam Neidhardt             AmazonCrossing
63742            Mercedes Pinto Maldonado          Amazon Publishing

[2777 rows x 6 columns]

In [31]:
incorrectly_encoded_df.head()

,ASIN,GROUP,FORMAT,TITLE,AUTHOR,PUBLISHER
12,3462046543,book,hardcover,"Ein Laden, der GlÃ¼ck verkauft",Beth Hoffman,Kiepenheuer & Witsch Gmbh
38,1420055720,book,hardcover,"Electric Machines: Steady State, Transients, a...","Ion Boldea, Lucian Nicolae Tutelea",CRC Press
46,1101946733,book,hardcover,SÃ©ance Infernale: A novel,Jonathan Skariton,Knopf
48,3407792913,book,hardcover,Der GrÃ¼ffelo,"Axel Scheffler, Julia Donaldson",Beltz
79,067402494X,book,hardcover,Self-Consciousness,Sebastian RÃ¶dl,Harvard University Press

In [32]:
incorrectly_encoded_df.count()

ASIN         2777
GROUP        2777
FORMAT       2777
TITLE        2777
AUTHOR       2774
PUBLISHER    2420
dtype: int64

In [33]:
import ftfy

# Function to fix text encoding issues
def fix_text_encoding(text):
    return ftfy.fix_text(text)

# Apply it to each column in the DataFrame
for col in raw_df.columns:
    raw_df[col] = raw_df[col].apply(lambda x: fix_text_encoding(x) if isinstance(x, str) else x)

# Display the updated DataFrame
print(raw_df.head(20))

          ASIN GROUP     FORMAT  \
0   1250150183  book  hardcover
1    778319997  book  hardcover
2   1608322564  book  hardcover
3    310325331  book  hardcover
4    312616295  book  hardcover
5   1250066190  book  hardcover
6   1592643124  book  hardcover
7   1849962839  book  hardcover
8   022640014X  book  hardcover
9   9176374343  book  hardcover
10  1599906953  book  hardcover
11  9176374408  book  hardcover
12  3462046543  book  hardcover
13   262035219  book  hardcover
14   735214468  book  hardcover
15   393292630  book  hardcover
16   727886274  book  hardcover
17  1845353498  book  hardcover
18  1405281197  book  hardcover
19  1405213930  book  hardcover

                                                TITLE  \
0   The Swamp: Washington's Murky Pool of Corrupti...
1             Rise and Shine, Benedict Stone: A Novel
2   Sell or Be Sold: How to Get Your Way in Busine...
3   Christian Apologetics: An Anthology of Primary...
4   Gravity: How the Weakest Force in the Universe...
5   Glass Houses: A Novel (Chief Inspector Gamache...
6                       Reference Guide to the Talmud
7   Induction Motor Control Design (Advances in In...
8   The Diversity Bargain: And Other Dilemmas of R...
9   White Fang (Wisehouse Classics - With Original...
10                                    Throne of Glass
11  Importance of Being Earnest (Wisehouse Classic...
12                      Ein Laden, der Glück verkauft
13                        Free Innovation (MIT Press)
14             In Trump We Trust: E Pluribus Awesome!
15  The Thin Light of Freedom: The Civil War and E...
16  Into the Grey: A feline-filled academic myster...
17                              The Beano Annual 2009
18            Official Lego (R) Star Wars Annual 2016
19                        Bob the Builder Annual 2005

                                               AUTHOR  \
0                                        Eric Bolling
1                                     Phaedra Patrick
2                                       Grant Cardone
3                  Khaldoun A. Sweis, Chad V. Meister
4                                         Brian Clegg
5                                        Louise Penny
6                               Rabbi Adin Steinsaltz
7   Riccardo Marino, Patrizio Tomei, Cristiano M. ...
8                                  Natasha K. Warikoo
9                                         Jack London
10                                      Sarah J. Maas
11                                        Oscar Wilde
12                                       Beth Hoffman
13                                    Eric von Hippel
14                                        Ann Coulter
15                                    Edward L. Ayers
16                                         Clea Simon
17                                            Various
18                                      Egmont UK Ltd
19                                               Anon

                      PUBLISHER
0            St. Martin's Press
1                Park Row Books
2    Greenleaf Book Group Press
3                     Zondervan
4            St. Martin's Press
5                Minotaur Books
6                The Toby Press
7                      Springer
8   University Of Chicago Press
9            Wisehouse Classics
10     Bloomsbury USA Childrens
11           Wisehouse Classics
12    Kiepenheuer & Witsch Gmbh
13                The MIT Press
14                     Sentinel
15       W. W. Norton & Company
16      Severn House Publishers
17                      Thomson
18             Egmont Books Ltd
19             Egmont Books Ltd

In [34]:
encoding_issues_pattern = r'[ÃÂâ€™â€œâ€¢Ã±Ã©Ã¼Ã¶â€•Ã¤â€“Ã¶ÃŸÃ³Ã¤Â¿ÃºÃ¡]'
incorrectly_encoded_titles = raw_df[raw_df['TITLE'].str.contains(encoding_issues_pattern, regex=True, na=False)]
print(incorrectly_encoded_titles[['TITLE']])

                                                   TITLE
968    ¿Eres tú mi mamá? (Are You My Mother? Spanish ...
5477   How to Use Graphic Design to Sell Things, Expl...
6017   ¡Esquivel! Un artista del sonido de la era esp...
6087   Are You My Mother?/¿Eres tú mi mamá? (The Cat ...
6339   The Illustrated Art of Manliness: The Essentia...
9788   50 chefs-d'œuvre que vous devez lire avant de ...
11619               FLOAT • Becoming Unstuck for Writers
13178  Cenerentola - La Cenicienta: Bilingue con test...
14102  ¿A dónde va Princesa Milena por primera vez?: ...
15248  Alexitimia, Un Mundo Sin Emociones: Aprende có...
15610  Psicología de las Emociones: Cómo usarlas a nu...
16468  Psicosomático I. Teoría Psicosomática: ¿Qué es...
21182  Mal de Alzheimer I, ¿Qué es? ¿Cuáles son sus C...
21259  Gagner en Bourse Grâce aux Dividendes (French ...
22354  ¿Y si comenzamos de nuevo? / Should We Start A...
23475  Ethereum: Manual para Invertir, crear y progra...
23731  Google Home - el manual completo: El guía para...
24447  Atteignez vos objectifs grâce à l'auto-hypnose...
26769  50 Chefs-D'œuvre Que Vous Devez Lire Avant De ...
28791  Manual de Amazon Echo: Tu guía de uso para Ale...
31076  MANUAL DE IOTA: Introducción a la Tecnología d...
31895  La culpa de Till (Landvik nº 3) (Spanish Edition)
33757  L'art du vide: Purifier son intérieur pour lib...
33870  Le Procédé Unique: Manifestez la richesse, l'a...
34897  El misterio de la casa abandonada: ¡Elige entr...
35367  Magnifico (romance y amor nº 1) (Spanish Edition)
35457  Recuperando a Tara (Spanish Language Edition) ...
37866  Gestión práctica de proyectos con Scrum: Desar...
38706  Espíritu Santo, ¡Sopla En Mí!: Aprendiendo los...
38751  Tocando el cielo de Manhattan: ¡En OFERTA! (RO...
38787  Capricho de un Fantasma: Cuando Callan las Alm...
41529  Am I small? ¿Soy pequeña?: Children's Picture ...
46140             O scurtă istorie ilustrată a românilor
47715  A Pilgrim's Guide to the Camino de Santiago: S...
47815  A Pilgrim's Guide to the Camino de Santiago: S...
47885  Munchen Venedig: Vom Marienplatz zum Markuspla...
48879  Jakobsweg Camino del Norte: Kustenweg von Irun...
49111  ¡Vuélvete Imparable! Volumen I (Volume 1) (Spa...
50504  ¿Has Llenado una Cubeta Hoy?: Una Guía Diaria ...
50885  Amintiri din România socialista (Romanian Edit...
51652  ¿Y si comenzamos de nuevo?: Cuando el arrepent...
55072  ¡No significa no!: Ensenandoles Limites Person...
55329                                     USA S�¼dwesten
55918     Handcraft Wire Jewelry: Chains•Clasps•Pendants
58493  ¿Has Llenado una Cubeta Hoy?: Una Guía Diaria ...
59270  L'art du vide: Purifier son intérieur pour lib...
59535  How to Sell Online: The experts¿ guide to maki...

In [35]:
incorrectly_encoded_titles[['TITLE']].count()

TITLE    47
dtype: int64

In [40]:
encoding_issues_pattern = r'[ÃÂâ€™â€œâ€¢Ã±Ã©Ã¼Ã¶â€•Ã¤â€“Ã¶ÃŸÃ³Ã¤Â¿ÃºÃ¡]'
incorrectly_encoded_author = raw_df[raw_df['AUTHOR'].str.contains(encoding_issues_pattern, regex=True, na=False)]
print(incorrectly_encoded_author[['AUTHOR']])

                                                  AUTHOR
1034   Andris Lagsdin, J. Kenji L¿pez-Alt, Jessie Ole...
5719                                        Leela AyyarÂ
7656        Will Goldfarb, Martin Westlake, Albert AdriÃ
8931                                   HÃ¥kan Gustavsson
53019                                        SaÅ¡a Jurić

In [41]:
incorrectly_encoded_author[['AUTHOR']].count()

AUTHOR    5
dtype: int64

In [63]:
raw_df.head(20)

,ASIN,GROUP,FORMAT,TITLE,AUTHOR,PUBLISHER
0,1250150183,book,hardcover,The Swamp: Washington's Murky Pool of Corrupti...,Eric Bolling,St. Martin's Press
1,778319997,book,hardcover,"Rise and Shine, Benedict Stone: A Novel",Phaedra Patrick,Park Row Books
2,1608322564,book,hardcover,Sell or Be Sold: How to Get Your Way in Busine...,Grant Cardone,Greenleaf Book Group Press
3,310325331,book,hardcover,Christian Apologetics: An Anthology of Primary...,"Khaldoun A. Sweis, Chad V. Meister",Zondervan
4,312616295,book,hardcover,Gravity: How the Weakest Force in the Universe...,Brian Clegg,St. Martin's Press
5,1250066190,book,hardcover,Glass Houses: A Novel (Chief Inspector Gamache...,Louise Penny,Minotaur Books
6,1592643124,book,hardcover,Reference Guide to the Talmud,Rabbi Adin Steinsaltz,The Toby Press
7,1849962839,book,hardcover,Induction Motor Control Design (Advances in In...,"Riccardo Marino, Patrizio Tomei, Cristiano M. ...",Springer
8,022640014X,book,hardcover,The Diversity Bargain: And Other Dilemmas of R...,Natasha K. Warikoo,University Of Chicago Press
9,9176374343,book,hardcover,White Fang (Wisehouse Classics - With Original...,Jack London,Wisehouse Classics
10,1599906953,book,hardcover,Throne of Glass,Sarah J. Maas,Bloomsbury USA Childrens
11,9176374408,book,hardcover,Importance of Being Earnest (Wisehouse Classic...,Oscar Wilde,Wisehouse Classics
12,3462046543,book,hardcover,"Ein Laden, der Glück verkauft",Beth Hoffman,Kiepenheuer & Witsch Gmbh
13,262035219,book,hardcover,Free Innovation (MIT Press),Eric von Hippel,The MIT Press
14,735214468,book,hardcover,In Trump We Trust: E Pluribus Awesome!,Ann Coulter,Sentinel
15,393292630,book,hardcover,The Thin Light of Freedom: The Civil War and E...,Edward L. Ayers,W. W. Norton & Company
16,727886274,book,hardcover,Into the Grey: A feline-filled academic myster...,Clea Simon,Severn House Publishers
17,1845353498,book,hardcover,The Beano Annual 2009,Various,Thomson
18,1405281197,book,hardcover,Official Lego (R) Star Wars Annual 2016,Egmont UK Ltd,Egmont Books Ltd
19,1405213930,book,hardcover,Bob the Builder Annual 2005,Anon,Egmont Books Ltd

In [42]:
encoding_issues_pattern = r'[ÃÂâ€™â€œâ€¢Ã±Ã©Ã¼Ã¶â€•Ã¤â€“Ã¶ÃŸÃ³Ã¤Â¿ÃºÃ¡]'
incorrectly_encoded_publisher = raw_df[raw_df['PUBLISHER'].str.contains(encoding_issues_pattern, regex=True, na=False)]
print(incorrectly_encoded_publisher[['PUBLISHER']])

Empty DataFrame
Columns: [PUBLISHER]
Index: []

In [54]:
encoding_issues_pattern = r'[ÃÂâ€™â€œâ€¢Ã±Ã©Â®Ã¼Ã¶â€•Ã¤â€“Ã¶ÃŸÃ³Ã¤Â¿ÃºÃ¡]'

# Detect rows with encoding issues, ignoring NaN values
incorrectly_encoded_titles = raw_df[raw_df['TITLE'].notna() & raw_df['TITLE'].str.contains(encoding_issues_pattern, regex=True, na=False)]
incorrectly_encoded_author = raw_df[raw_df['AUTHOR'].notna() & raw_df['AUTHOR'].str.contains(encoding_issues_pattern, regex=True, na=False)]
incorrectly_encoded_publisher = raw_df[raw_df['PUBLISHER'].notna() & raw_df['PUBLISHER'].str.contains(encoding_issues_pattern, regex=True, na=False)]

# Combine all the problematic rows (only those with encoding issues, not NaN)
rows_to_drop = pd.concat([incorrectly_encoded_titles, incorrectly_encoded_author, incorrectly_encoded_publisher])

# Drop the rows with encoding issues from the original DataFrame
raw_df_cleaned2 = raw_df.drop(rows_to_drop.index)

# Display info about the cleaned DataFrame
print(raw_df_cleaned2.info())

# Display the first 20 rows of the cleaned DataFrame for verification
print(raw_df_cleaned2.head(20))

<class 'pandas.core.frame.DataFrame'>
Index: 63598 entries, 0 to 63747
Data columns (total 6 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   ASIN       63598 non-null  object
 1   GROUP      63598 non-null  object
 2   FORMAT     63597 non-null  object
 3   TITLE      63597 non-null  object
 4   AUTHOR     63511 non-null  object
 5   PUBLISHER  57145 non-null  object
dtypes: object(6)
memory usage: 3.4+ MB
None
          ASIN GROUP     FORMAT  \
0   1250150183  book  hardcover
1    778319997  book  hardcover
2   1608322564  book  hardcover
3    310325331  book  hardcover
4    312616295  book  hardcover
5   1250066190  book  hardcover
6   1592643124  book  hardcover
7   1849962839  book  hardcover
8   022640014X  book  hardcover
9   9176374343  book  hardcover
10  1599906953  book  hardcover
11  9176374408  book  hardcover
12  3462046543  book  hardcover
13   262035219  book  hardcover
14   735214468  book  hardcover
15   393292630  book  hardcover
16   727886274  book  hardcover
17  1845353498  book  hardcover
18  1405281197  book  hardcover
19  1405213930  book  hardcover

                                                TITLE  \
0   The Swamp: Washington's Murky Pool of Corrupti...
1             Rise and Shine, Benedict Stone: A Novel
2   Sell or Be Sold: How to Get Your Way in Busine...
3   Christian Apologetics: An Anthology of Primary...
4   Gravity: How the Weakest Force in the Universe...
5   Glass Houses: A Novel (Chief Inspector Gamache...
6                       Reference Guide to the Talmud
7   Induction Motor Control Design (Advances in In...
8   The Diversity Bargain: And Other Dilemmas of R...
9   White Fang (Wisehouse Classics - With Original...
10                                    Throne of Glass
11  Importance of Being Earnest (Wisehouse Classic...
12                      Ein Laden, der Glück verkauft
13                        Free Innovation (MIT Press)
14             In Trump We Trust: E Pluribus Awesome!
15  The Thin Light of Freedom: The Civil War and E...
16  Into the Grey: A feline-filled academic myster...
17                              The Beano Annual 2009
18            Official Lego (R) Star Wars Annual 2016
19                        Bob the Builder Annual 2005

                                               AUTHOR  \
0                                        Eric Bolling
1                                     Phaedra Patrick
2                                       Grant Cardone
3                  Khaldoun A. Sweis, Chad V. Meister
4                                         Brian Clegg
5                                        Louise Penny
6                               Rabbi Adin Steinsaltz
7   Riccardo Marino, Patrizio Tomei, Cristiano M. ...
8                                  Natasha K. Warikoo
9                                         Jack London
10                                      Sarah J. Maas
11                                        Oscar Wilde
12                                       Beth Hoffman
13                                    Eric von Hippel
14                                        Ann Coulter
15                                    Edward L. Ayers
16                                         Clea Simon
17                                            Various
18                                      Egmont UK Ltd
19                                               Anon

                      PUBLISHER
0            St. Martin's Press
1                Park Row Books
2    Greenleaf Book Group Press
3                     Zondervan
4            St. Martin's Press
5                Minotaur Books
6                The Toby Press
7                      Springer
8   University Of Chicago Press
9            Wisehouse Classics
10     Bloomsbury USA Childrens
11           Wisehouse Classics
12    Kiepenheuer & Witsch Gmbh
13                The MIT Press
14                     Sentinel
15       W. W. Norton & Company
16      Severn House Publishers
17                      Thomson
18             Egmont Books Ltd
19             Egmont Books Ltd

In [49]:
raw_df.count()

ASIN         63748
GROUP        63748
FORMAT       63747
TITLE        63747
AUTHOR       63661
PUBLISHER    57263
dtype: int64

In [55]:
raw_df_cleaned2.count()

ASIN         63598
GROUP        63598
FORMAT       63597
TITLE        63597
AUTHOR       63511
PUBLISHER    57145
dtype: int64

In [56]:
raw_df_cleaned2 = raw_df_cleaned2[raw_df['ASIN'] != 'M."']

# Display the updated DataFrame after dropping rows
print(raw_df_cleaned2)

             ASIN GROUP     FORMAT  \
0      1250150183  book  hardcover
1       778319997  book  hardcover
2      1608322564  book  hardcover
3       310325331  book  hardcover
4       312616295  book  hardcover
...           ...   ...        ...
63743   976986280  book  paperback
63744  1626396078  book  paperback
63745  3866863411  book  paperback
63746   425250415  book  paperback
63747  9734611526  book  paperback

                                                   TITLE  \
0      The Swamp: Washington's Murky Pool of Corrupti...
1                Rise and Shine, Benedict Stone: A Novel
2      Sell or Be Sold: How to Get Your Way in Busine...
3      Christian Apologetics: An Anthology of Primary...
4      Gravity: How the Weakest Force in the Universe...
...                                                  ...
63743  From the Coffee House of Jewish Dreamers: Poem...
63744                            Midnight at the Orpheus
63745                   Portugal Spanien: Via Algarviana
63746    The Coyote Tracker (Josiah Wolfe, Texas Ranger)
63747  Puls. Manual de limba romana pentru straini. C...

                                   AUTHOR                   PUBLISHER
0                            Eric Bolling          St. Martin's Press
1                         Phaedra Patrick              Park Row Books
2                           Grant Cardone  Greenleaf Book Group Press
3      Khaldoun A. Sweis, Chad V. Meister                   Zondervan
4                             Brian Clegg          St. Martin's Press
...                                   ...                         ...
63743                     Isidore Century            Ben Yehuda Press
63744                  Alyssa Linn Palmer          Bold Strokes Books
63745                Christiane Heitzmann        Stein, Conrad Verlag
63746                     Larry D. Sweazy                     Berkley
63747                        Daniela Kohn             Editura Polirom

[63597 rows x 6 columns]

C:\Users\Admin\AppData\Local\Temp\ipykernel_7116\2369639094.py:1: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  raw_df_cleaned2 = raw_df_cleaned2[raw_df['ASIN'] != 'M."']

In [57]:
raw_df_cleaned2 = raw_df_cleaned2[raw_df['ASIN'] != 'L"']

# Display the updated DataFrame after dropping rows
print(raw_df_cleaned2)

             ASIN GROUP     FORMAT  \
0      1250150183  book  hardcover
1       778319997  book  hardcover
2      1608322564  book  hardcover
3       310325331  book  hardcover
4       312616295  book  hardcover
...           ...   ...        ...
63743   976986280  book  paperback
63744  1626396078  book  paperback
63745  3866863411  book  paperback
63746   425250415  book  paperback
63747  9734611526  book  paperback

                                                   TITLE  \
0      The Swamp: Washington's Murky Pool of Corrupti...
1                Rise and Shine, Benedict Stone: A Novel
2      Sell or Be Sold: How to Get Your Way in Busine...
3      Christian Apologetics: An Anthology of Primary...
4      Gravity: How the Weakest Force in the Universe...
...                                                  ...
63743  From the Coffee House of Jewish Dreamers: Poem...
63744                            Midnight at the Orpheus
63745                   Portugal Spanien: Via Algarviana
63746    The Coyote Tracker (Josiah Wolfe, Texas Ranger)
63747  Puls. Manual de limba romana pentru straini. C...

                                   AUTHOR                   PUBLISHER
0                            Eric Bolling          St. Martin's Press
1                         Phaedra Patrick              Park Row Books
2                           Grant Cardone  Greenleaf Book Group Press
3      Khaldoun A. Sweis, Chad V. Meister                   Zondervan
4                             Brian Clegg          St. Martin's Press
...                                   ...                         ...
63743                     Isidore Century            Ben Yehuda Press
63744                  Alyssa Linn Palmer          Bold Strokes Books
63745                Christiane Heitzmann        Stein, Conrad Verlag
63746                     Larry D. Sweazy                     Berkley
63747                        Daniela Kohn             Editura Polirom

[63596 rows x 6 columns]

C:\Users\Admin\AppData\Local\Temp\ipykernel_7116\251500125.py:1: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  raw_df_cleaned2 = raw_df_cleaned2[raw_df['ASIN'] != 'L"']

In [58]:
raw_df_cleaned2.count()

ASIN         63596
GROUP        63596
FORMAT       63596
TITLE        63596
AUTHOR       63511
PUBLISHER    57145
dtype: int64

In [66]:
# Save the DataFrame as a CSV file without the index column
raw_df_cleaned2.to_csv('final_cleaned_amazon_extras2.csv', index=False,encoding='utf-8')

In [62]:
unique_counts = raw_df_cleaned2.nunique()

# Print the unique counts
print(unique_counts)

ASIN         63591
GROUP            2
FORMAT           4
TITLE        58117
AUTHOR       34135
PUBLISHER     9047
dtype: int64